language: php
php:
        - 5.6
        - 5.5
        - 5.4
        - 5.3

before_script:
        - composer install --dev --no-interaction

script:
        - make tests=skip
        - mkdir -p build/logs
        - phpunit -c phpunit.xml --coverage-clover build/logs/clover.xml

after_script:
        - php vendor/bin/coveralls -v
